[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Origin = "https://free-tabs.netlify.app"

[[redirects]]
  from = "/api/*"
  to = "https://my-backend-expressjs.up.railway.app/:splat"
  status = 200
  force = true
